### PR TITLE
Update test_svdd.py

### PR DESCRIPTION
**Pull request by bachboss**
I run into this problem of "DLL load failed: %1 is not a valid Win32 application.”

Changed the order of import and it turn out ok.

### CODE REVIEW

**Comment by nicococo** [comment]
Awesome! Thank you.

**Comment by ahmadabp** [comment]
HI
how can i import SVDD algorithm?

**Comment by nicococo** [comment]
Hi, there are 2 vanilla SVDD formulations available: 

1. tilitools/svdd_dual_qp
2.  tilitools/svdd_primal_sgd

**Comment by ahmadabp** [comment]
thank u

**Comment by ahmadabp** [comment]
hi dear
I visited SVDD code in python as u advised but i can not understand
parameters for SVDD and could u please send me a exercise for using these
parameters for classification.
thank you

**Pull request merged**
